# Generated by Django 4.1 on 2022-09-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTransaccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
