# Generated by Django 4.1 on 2022-09-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTransaccion', '0002_alter_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
    ]
