# Generated by Django 4.1 on 2022-09-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTransaccion', '0003_remove_usuario_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personas',
            old_name='id_usuario',
            new_name='id_persona',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='empresas_id_empresa_id',
            new_name='id_empresa',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='personas_id_usuarios_id',
            new_name='id_personas',
        ),
        migrations.RemoveField(
            model_name='transacciones',
            name='usuario_id_usuario',
        ),
        migrations.AddField(
            model_name='transacciones',
            name='id_usuario_tran',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='apellidos',
            field=models.TextField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='nombre',
            field=models.TextField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionTransaccion.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.TextField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.TextField(max_length=45, null=True),
        ),
    ]
