# Generated by Django 4.1 on 2022-09-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTransaccion', '0004_rename_id_usuario_personas_id_persona_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_personas',
            new_name='id_persona',
        ),
    ]
