# Generated by Django 4.1 on 2022-09-17 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTransaccion', '0005_rename_id_personas_usuario_id_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacciones',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='transacciones',
            name='id_usuario_tran',
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTransaccion.empresa'),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTransaccion.usuario'),
        ),
    ]
